a=float(input("input value of a= "))
b=float(input("input value of b= "))
c=float(input("input value of c= "))
x1=((-b)+(((b**2)-4*a*c)**(.5)))/(2*a)
x2=((-b)-(((b**2)-4*a*c)**(.5)))/(2*a)
print(x1)
print(x2)
